// pair-device — Edge Function (Phase 3: device/register pairing)
//
// The ONE deliberately-anonymous entry point in the app: a fresh tablet
// has no Supabase session at all before pairing, so this function accepts
// requests with NO Authorization header. It validates a short-lived,
// single-use 6-character pairing code (generated by an admin from
// Settings → Devices) and, on success, mints a real (but human-invisible)
// Supabase Auth user for the device — the same shape create-cashier
// already uses for cashiers — so the device's browser can stay signed in
// indefinitely afterward and everything built on auth_store_id()/RLS just
// works for it, with zero new authorization mechanism.
//
// Flow:
//   1. Validate the request body.
//   2. Use the service_role client to call _validate_pairing_code(), a
//      security definer function not granted to any client role — only
//      reachable here.
//   3. On success, create a new auth user (random email/password, never
//      surfaced to a human) — this fires the same handle_new_user trigger
//      create-cashier relies on, which always attaches a brand-new
//      throwaway store to any new auth.users row. Delete that throwaway
//      store (cascades the throwaway staff row), then insert the real
//      `devices` row pointing at the validated store.
//   4. Mark the pairing code consumed (via _consume_pairing_code, using
//      the now-real device id).
//   5. Return the transient email/password for the client to immediately
//      sign in with and discard — never persisted or logged beyond this
//      one response.

import { createClient } from "jsr:@supabase/supabase-js@2";

const allowedOrigins = (Deno.env.get("ALLOWED_ORIGINS") ?? "")
  .split(",")
  .map((o) => o.trim())
  .filter(Boolean);

function corsHeaders(req: Request): Record<string, string> {
  const origin = req.headers.get("Origin") ?? "";
  const headers: Record<string, string> = {
    "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
    Vary: "Origin",
  };
  if (allowedOrigins.includes(origin)) {
    headers["Access-Control-Allow-Origin"] = origin;
  }
  return headers;
}

function randomPassword(): string {
  const bytes = new Uint8Array(18);
  crypto.getRandomValues(bytes);
  return Array.from(bytes, (b) => b.toString(36).padStart(2, "0")).join("").slice(0, 24);
}

Deno.serve(async (req) => {
  const cors = corsHeaders(req);
  const json = (body: unknown, status: number) =>
    new Response(JSON.stringify(body), { status, headers: { ...cors, "Content-Type": "application/json" } });

  if (req.method === "OPTIONS") {
    return new Response("ok", { headers: cors });
  }

  try {
    let body: { code?: string; deviceName?: string };
    try {
      body = await req.json();
    } catch {
      return json({ error: "Request body must be valid JSON" }, 400);
    }

    const code = body.code?.trim().toUpperCase();
    const deviceName = body.deviceName?.trim();
    if (!code || code.length !== 6 || !deviceName) {
      return json({ error: "A 6-character code and a device name are required" }, 400);
    }

    const supabaseUrl = Deno.env.get("SUPABASE_URL")!;
    const serviceRoleKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
    const adminClient = createClient(supabaseUrl, serviceRoleKey);

    const { data: validation, error: validateError } = await adminClient
      .rpc("_validate_pairing_code", { p_code: code })
      .single();

    if (validateError) {
      console.error("pair-device: _validate_pairing_code failed:", validateError.message);
      return json({ error: "Could not validate this code. Try again." }, 500);
    }

    if (!validation?.ok || !validation.store_id || !validation.created_by) {
      return json({ error: "INVALID_OR_EXPIRED_CODE" }, 400);
    }

    const { store_id: storeId, store_name: storeName, created_by: pairedBy, pairing_code_id: pairingCodeId } =
      validation;

    const email = `device+${crypto.randomUUID()}@internal.invalid`;
    const password = randomPassword();

    const { data: created, error: createError } = await adminClient.auth.admin.createUser({
      email,
      password,
      email_confirm: true,
    });

    if (createError || !created.user) {
      console.error("pair-device: createUser failed:", createError?.message);
      return json({ error: "Could not pair this device. Try again." }, 400);
    }

    const newDeviceId = created.user.id;

    // Defense in depth: generate_pairing_code() already checked this before
    // issuing the code, but re-check right before the insert to close the
    // race where a code was generated moments before the store's plan was
    // downgraded to tindahan, or two codes were issued back-to-back.
    const { data: targetStore } = await adminClient
      .from("stores")
      .select("plan")
      .eq("id", storeId)
      .single();

    if (targetStore?.plan === "tindahan") {
      const { count: activeDeviceCount } = await adminClient
        .from("devices")
        .select("id", { count: "exact", head: true })
        .eq("store_id", storeId)
        .is("unpaired_at", null);

      if ((activeDeviceCount ?? 0) >= 1) {
        await adminClient.auth.admin.deleteUser(newDeviceId);
        return json({ error: "DEVICE_LIMIT_REACHED" }, 400);
      }
    }

    // The trigger just gave this new auth user a throwaway store as its
    // admin. Remove it, then attach the real devices row to the store the
    // pairing code actually belongs to.
    const { data: throwawayStaff } = await adminClient
      .from("staff")
      .select("store_id")
      .eq("id", newDeviceId)
      .single();

    if (throwawayStaff?.store_id) {
      await adminClient.from("stores").delete().eq("id", throwawayStaff.store_id);
      // ^ cascades and deletes the throwaway staff row too
    }

    const { error: insertError } = await adminClient.from("devices").insert({
      id: newDeviceId,
      store_id: storeId,
      name: deviceName,
      paired_by: pairedBy,
    });

    if (insertError) {
      await adminClient.auth.admin.deleteUser(newDeviceId);
      return json({ error: insertError.message }, 400);
    }

    await adminClient.rpc("_consume_pairing_code", {
      p_pairing_code_id: pairingCodeId,
      p_device_id: newDeviceId,
    });

    return json({ email, password, storeName }, 201);
  } catch (err) {
    return json({ error: err instanceof Error ? err.message : "Unexpected error" }, 500);
  }
});
